[package]
name = "pdfwc"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
mupdf = "0.3"
clap = "3"
env_logger = "0.9"
log = "0.4"
